(defn elem-op [op] (fn [& args] (apply mapv op args)))
(defn map-op [op] (fn [a b] (mapv #(op % b) a)))
(defn shapeless-op [op] (fn this [& args] (if (number? (first args)) (apply op args) (apply mapv this args))))

(def v+ (elem-op +))
(def v- (elem-op -))
(def v* (elem-op *))
(def vd (elem-op /))
(def v*s (map-op *))
(defn scalar [& args] (reduce + (apply v* args)))
(defn vect [v1 v2] [( - (* (nth v1 1) (nth v2 2)) (* (nth v1 2) (nth v2 1)))
                    ( - (* (nth v1 2) (nth v2 0)) (* (nth v1 0) (nth v2 2)))
                    ( - (* (nth v1 0) (nth v2 1)) (* (nth v1 1) (nth v2 0)))])

(def m+ (elem-op v+))
(def m- (elem-op v-))
(def m* (elem-op v*))
(def md (elem-op vd))
(def m*s (map-op v*s))
(def m*v (map-op scalar))
(defn transpose [m] (apply mapv vector m))
(defn m*m [m1 m2] (let [tm2 (transpose m2)] (mapv #(m*v tm2 %) m1)))

(def s+ (shapeless-op +))
(def s- (shapeless-op -))
(def s* (shapeless-op *))
(def sd (shapeless-op /))